# Generated by Django 6.0.1 on 2026-01-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('member_count', models.PositiveIntegerField(default=1)),
                ('ticket_count', models.PositiveIntegerField(default=0)),
                ('tasks_to_do_count', models.PositiveIntegerField(default=0)),
                ('tasks_high_prio_count', models.PositiveIntegerField(default=0)),
                ('owner_id', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('priority', models.CharField(max_length=50)),
                ('assignee_id', models.PositiveIntegerField(blank=True, null=True)),
                ('reviewer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('comments_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
